version: '3.8'

services:
  # --- NOSSO PAINEL E ROBÔS ---
  app-rpa:
    build: .
    container_name: onesid-rpa-panel
    restart: always
    ports:
      - "5000:5000" # Porta para você acessar no navegador
    volumes:
      - .:/app # Permite que alterações no código reflitam sem recriar o container
    depends_on:
      - db
      - loki
    networks:
      - onesid-net

  # --- BANCO DE DADOS ---
  db:
    image: postgres:15-alpine
    container_name: onesid-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onesid_db
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
    networks:
      - onesid-net

  # --- LOKI (Coletor de Logs) ---
  loki:
    image: grafana/loki:2.9.2
    container_name: onesid-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - onesid-net

networks:
  onesid-net:
    driver: bridge